DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

TOKEN_TYPE_BEARER = "bearer"

ACTIVITY_ENTITY_USER = "user"
ACTIVITY_ENTITY_WORKSPACE = "workspace"
ACTIVITY_ENTITY_PROJECT = "project"
ACTIVITY_ENTITY_TASK = "task"
ACTIVITY_ENTITY_COMMENT = "comment"
ACTIVITY_ENTITY_NOTIFICATION = "notification"
